version: '3.8'

services:
  weather-synth:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    image: weather-synth:latest
    container_name: weather-synth-app
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - weather-synth-network
    volumes:
      # Optional: Mount logs for debugging
      - ./logs:/var/log/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weather-synth.rule=Host(`weather.localhost`)"
      - "traefik.http.routers.weather-synth.entrypoints=web"
      - "traefik.http.services.weather-synth.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Add Traefik reverse proxy for production
  # traefik:
  #   image: traefik:v2.9
  #   container_name: weather-synth-traefik
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./traefik.yml:/traefik.yml:ro
  #   networks:
  #     - weather-synth-network

networks:
  weather-synth-network:
    driver: bridge

volumes:
  weather-synth-logs:
    driver: local 