version: '3.8'

services:
  weather-synth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - LAUNCHDARKLY_SDK_KEY=${LAUNCHDARKLY_SDK_KEY:-"demo-server-key"}
      - REACT_APP_LAUNCHDARKLY_CLIENT_ID=${REACT_APP_LAUNCHDARKLY_CLIENT_ID:-"your-client-sdk-key-here"}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weather-synth.rule=Host(`weather-synth.local`)"
      - "traefik.http.services.weather-synth.loadbalancer.server.port=80"

  # Local development service
  weather-synth-local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - LAUNCHDARKLY_SDK_KEY=${LAUNCHDARKLY_SDK_KEY}
      - REACT_APP_LAUNCHDARKLY_CLIENT_ID=${REACT_APP_LAUNCHDARKLY_CLIENT_ID}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - VISUAL_CROSSING_API_KEY=${VISUAL_CROSSING_API_KEY}
      - REACT_APP_GA_MEASUREMENT_ID=${REACT_APP_GA_MEASUREMENT_ID}
      - REACT_APP_WEATHERAPI_API_KEY=${REACT_APP_WEATHERAPI_API_KEY}
      - REACT_APP_TOMORROWIO_API_KEY=${REACT_APP_TOMORROWIO_API_KEY}
      - WEATHERAPI_API_KEY=${WEATHERAPI_API_KEY}
    restart: unless-stopped
    profiles:
      - local

  # Development service (optional)
  weather-synth-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    profiles:
      - dev
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro 