name: LaunchDarkly Code References

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  launchdarkly-code-references:
    runs-on: ubuntu-latest
    name: Find LaunchDarkly flag references
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 11 # This value must be set if the lookback configuration option is not disabled for find-code-references. You may want to increase this value if your last commit was further back than 10 commits.

      - name: Find code references
        uses: launchdarkly/find-code-references@v2.13.0
        with:
          accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
          projKey: ${{ secrets.LD_PROJECT_KEY }} 